apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-demo
  namespace: demo2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-demo
  template:
    metadata:
      labels:
        app: echo-demo
    spec:
      containers:
      - name: echo
        image: nginxdemos/hello
        ports:
        - containerPort: 80
