apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-demo
  namespace: demo2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-demo
  template:
    metadata:
      labels:
        app: echo-demo
    spec:
      containers:
        - name: http-echo
          image: nginxdemos/hello:plain-text
          args:
            - "-text=hello from echo-demo"
          ports:
            - containerPort: 80
