apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  name: echo-config
  namespace: crossplane-system
spec:
  forProvider:
    manifest:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: echo-config
        namespace: demo2
      data:
        MESSAGE: "I broke hello from crossplane"
  providerConfigRef:
    name: kubernetes-provider
